apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-mart-deployment
  labels:
    app: e-mart
spec:
  replicas: 3
  selector:
    matchLabels:
      app: e-mart
  template:
    metadata:
      labels:
        app: e-mart
    spec:
      containers:
      - name: e-mart-container
        image: kiranimg/e-mart:latest
        ports:
        - containerPort: 80
